---
- name: OS tweaks for production kubernetes
  hosts: all
  become: true
  tasks:
    # https://github.com/lxc/lxd/blob/master/doc/production-setup.md
    - name: limit - nofile - soft - everyone
      community.general.pam_limits:
        domain: "*"
        limit_item: nofile
        limit_type: soft
        value: 1048576
    - name: limit - nofile - hard - everyone
      community.general.pam_limits:
        domain: "*"
        limit_item: nofile
        limit_type: hard
        value: 1048576
    - name: limit - nofile - soft - root
      community.general.pam_limits:
        domain: root
        limit_item: nofile
        limit_type: soft
        value: 1048576
    - name: limit - nofile - hard - root
      community.general.pam_limits:
        domain: root
        limit_item: nofile
        limit_type: hard
        value: 1048576

    - name: limit - memlock - soft - everyone
      community.general.pam_limits:
        domain: "*"
        limit_item: memlock
        limit_type: soft
        value: unlimited
    - name: limit - memlock - hard - everyone
      community.general.pam_limits:
        domain: "*"
        limit_item: memlock
        limit_type: hard
        value: unlimited
    - name: limit - memlock - soft - root
      community.general.pam_limits:
        domain: root
        limit_item: memlock
        limit_type: soft
        value: unlimited
    - name: limit - memlock - hard - root
      community.general.pam_limits:
        domain: root
        limit_item: memlock
        limit_type: hard
        value: unlimited

    # These have been worked out through trial and error
    - name: set fs.file-max sysctl
      ansible.posix.sysctl:
        name: fs.file-max
        value: 2097152
        sysctl_file: /etc/sysctl.d/50-kubernetes.conf

    - name: set fs.inotify.max_queued_events sysctl
      ansible.posix.sysctl:
        name: fs.inotify.max_queued_events
        value: 65536
        sysctl_file: /etc/sysctl.d/50-kubernetes.conf

    - name: set fs.inotify.max_user_instances sysctl
      ansible.posix.sysctl:
        name: fs.inotify.max_user_instances
        value: 8192
        sysctl_file: /etc/sysctl.d/50-kubernetes.conf

    - name: set fs.inotify.max_user_watches sysctl
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: 524288
        sysctl_file: /etc/sysctl.d/50-kubernetes.conf

    - name: set kernel.keys.maxkeys sysctl
      ansible.posix.sysctl:
        name: kernel.keys.maxkeys
        value: 2000
        sysctl_file: /etc/sysctl.d/50-kubernetes.conf

    - name: set kernel.keys.maxbytes sysctl
      ansible.posix.sysctl:
        name: kernel.keys.maxbytes
        value: 2000000
        sysctl_file: /etc/sysctl.d/50-kubernetes.conf
